#!/bin/bash

# Bash script with frequently used commands

case "$1" in
    compile)
        echo "Compiling for linux."
        gcc -o bin/main src/main.c -I./SDL3/linux/include -L./SDL3/linux/lib -lSDL3 -lm
    ;;
    compilewindows)
        echo "Compiling for windows."
        x86_64-w64-mingw32-gcc -o bin/main.exe src/main.c -I./SDL3/windows/include -L./SDL3/windows/lib -lmingw32 -lSDL3
    ;;
    run)
        ./bin/linux/main
    ;;
    runwindows)
        ./bin/windows/main.exe
    ;;
    
    dev)
        echo "Compiling and running on windows."
        x86_64-w64-mingw32-gcc -o bin/main.exe src/main.c -I./SDL3/windows/include -L./SDL3/windows/lib -lmingw32 -lSDL3 -lm
        if [ $? -eq 0 ]; then
            ./bin/windows/main.exe
        fi
    ;;
    *)
        echo "Unknown command."
    ;;
esac